version: "3.9"

services:
  reverse-jupyter:
    build: .
    container_name: reverse-jupyter
    ports:
      - "2222:8888"                 # Jupyter наружу
    environment:
      - JUPYTER_TOKEN=123
    volumes:
      # ноутбуки и скрипты
      - ./notebooks:/workspace
      # Каталог с YARA-правилами
      - ./yara:/yara
